In [1]:
import numpy as np

Creating an 4x4 matrix with range values (1-16)

creating a 4x4 matric with 1-16 range numbers

In [2]:
A = np.arange(1,17).reshape((4,4))

A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Create accumulator array for new layer

In [3]:
stride = (2, 2)
ashape = A.shape
# ACC = np.zeros((int((ashape[0]/stride[0])), int((ashape[1]/stride[1]))))
ACC = np.zeros(4)
ACIDX = np.zeros(4)
ACIDY = np.zeros(4)
ACC

array([0., 0., 0., 0.])

In [4]:
ACIDX

array([0., 0., 0., 0.])

Apply the maxpool filter

In [8]:
idx = 0
for y in range(0, ashape[0], stride[0]):
    for x in range(0, ashape[1], stride[1]):
        kernelA = A[y:(y+stride[0]),x:(x+stride[1])]
        max = 0
        x_ind = 0
        y_ind = 0
        for winy in kernelA:
            x_ind = 0
            for winx in winy:
                if winx > max:
                    max = winx
                    ACIDY[idx] = y_ind
                    ACIDX[idx] = x_ind
                x_ind = x_ind + 1
            y_ind = y_ind + 1
        ACC[idx] = max
        idx = idx + 1
ACC = ACC.reshape(stride)
print(ACC)


[[ 6.  8.]
 [14. 16.]]


index store of max indexes of Y and X

In [6]:
print(ACIDX)
print(ACIDY)

[1. 1. 1. 1.]
[1. 1. 1. 1.]


In [14]:
UA = np.zeros(16).reshape((4,4))
UA

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
flatmax = ACC.reshape((4,))
idx = 0
for y in range(0, ashape[0], stride[0]):
    for x in range(0, ashape[1], stride[1]):
        x_pos = int(ACIDX[idx])
        y_pos = int(ACIDY[idx])
        UA[y:(y+stride[0]),x:(x+stride[1])][y_pos, x_pos] = flatmax[idx]
        idx = idx + 1
print(UA)

[[ 0.  0.  0.  0.]
 [ 0.  6.  0.  8.]
 [ 0.  0.  0.  0.]
 [ 0. 14.  0. 16.]]
