In [1]:
import numpy as np

create a sigmoid activiation function $\frac{1}{1+e^-x}$

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

For learning and adjust weights it should be created the activation function derivative
$x*(1-x)$

In [3]:
def sigmoid_derivative(x):
    return x*(1-x)

Create a Training dataset, which are seperated by X as input as Y as output Axis

In [5]:
training_inputs = np.array([[0,0,1],
                           [1,1,1],
                           [1,0,1],
                           [0,1,1]])
training_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [7]:
training_outputs = np.array([[0,1,1,0]]).T
training_outputs

array([[0],
       [1],
       [1],
       [0]])

Creating a weight matrix with random inititalization

In [8]:
weights = 2 * np.random.random((3,1))-1
weights

array([[-0.86815017],
       [-0.34916686],
       [-0.04845903]])

lets do the training in 1 epoch, to adjust the weights with loss function to call the error value with activatio function derivative with 0.01 learing rate. The calculation: $error = (Y-\hat{Y})^2$, where the Y is the $train output$ and $\hat{Y}$ the output from neural network. After the loss calculation, we calculate the adjustment weight from function derivative: $adjustment=error * [output*(1-output)]$ where the valuas are trivial. Lastly it adjust the weight by: $weight =weight-0.01*(input^T*adjustment)$

In [16]:
learing_rate=0.01
for epoch in range(1):
    input = training_inputs
    outputs = sigmoid(np.dot(input, weights))
    error = (training_outputs - outputs)**2
    error
    adjustment = error * sigmoid_derivative(outputs)
    weights = weights - learing_rate * (np.dot(input.T,adjustment))

ajdusted weights

In [17]:
weights

array([[-0.0004055 ],
       [-0.00106594],
       [-0.0019281 ]])

adjustment

In [18]:
adjustment

array([[0.06253568],
       [0.06240019],
       [0.06241166],
       [0.06254715]])